# Generated by Django 2.1.3 on 2018-11-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181107_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Motor',
        ),
    ]
