# Generated by Django 2.1.3 on 2018-11-09 01:01

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181108_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('brand', models.CharField(max_length=120, null=True)),
                ('reference', models.CharField(max_length=20, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('image_1', models.ImageField(null=True, upload_to=products.models.upload_image)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_6', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_7', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_8', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('brand', models.CharField(max_length=120, null=True)),
                ('reference', models.CharField(max_length=20, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('image_1', models.ImageField(null=True, upload_to=products.models.upload_image)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_6', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_7', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_8', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
