# Generated by Django 2.1.3 on 2018-11-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_electronic_fashion'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fashion',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
