# Generated by Django 2.1.3 on 2018-11-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181108_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fashion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
