# Generated by Django 2.1.3 on 2018-11-09 21:19

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181108_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('brand', models.CharField(max_length=120, null=True)),
                ('reference', models.CharField(max_length=20, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('image_1', models.ImageField(null=True, upload_to=products.models.upload_image)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_6', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_7', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('image_8', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Electronic',
        ),
        migrations.DeleteModel(
            name='Motor',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='price',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='title',
        ),
        migrations.AddField(
            model_name='fashion',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
