# Generated by Django 2.1.3 on 2018-12-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
